apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cluster }}-selenium-GROUPS-URL-cronjob
  namespace: tester-pipelines
spec:
  schedule: "SCHEDULE" # HUMAN_READALBE
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: selenium-GROUPS-URL-cronjob-trigger
            image: {{ .Values.baseImageRegistry }}/ffe-curl:0.0.1
            args: ["curl", "-X", "POST", "--data", "{}", "el-{{ .Values.cluster }}-selenium-GROUPS-URL-cronjob.tester-pipelines.svc.cluster.local:8080"]
            envFrom:
              - configMapRef:
                  name: cms-ffm-selnium-cronjob-env-ops
          restartPolicy: Never