apiVersion: batch/v1
kind: CronJob
metadata:
  name: CLEAN_GROUPS-URL-CLEAN_RELEASE_BRANCH-cj
  namespace: tester-pipelines
spec:
  schedule: "SCHEDULE" # HUMAN_READALBE
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: CLEAN_GROUPS-URL-CLEAN_RELEASE_BRANCH-cj-trigger
            image: {{ .Values.baseImageRegistry }}/ffe-curl:0.0.1
            args: ["curl", "-X", "POST", "--data", "{}", "el-CLEAN_GROUPS-URL-CLEAN_RELEASE_BRANCH-cronjob.tester-pipelines.svc.cluster.local:8080"]
            envFrom:
              - configMapRef:
                  name: cms-ffm-selnium-cronjob-env-ops
          restartPolicy: Never