apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: CLEAN_GROUPS-URL-CLEAN_RELEASE_BRANCH-cronjob
  namespace: tester-pipelines
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: CLEAN_GROUPS-URL-CLEAN_RELEASE_BRANCH-cronjob-binding
      name: CLEAN_GROUPS-URL-CLEAN_RELEASE_BRANCH-cj-trigger
      template:
        ref: CLEAN_GROUPS-URL-CLEAN_RELEASE_BRANCH-cronjob-tt